version: '3.1'

services:

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d

  build: &build
    build:
      context: .
      args:
        NODE_IMAGE: "node:${NODE_VERSION}-alpine"
    environment:
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: password
    volumes:
      - ../../:/app
    working_dir: /app/packages/example
    restart: on-failure
    depends_on:
      - db
    command: node /app/packages/cli/lib/index.js --config config.json

  watch:
    <<: *build
    command: npx pgtyped --watch --config config.json

  test:
    <<: *build
    depends_on:
      - build
    command: node lib/index.js

  test-cjs:
    <<: *build
    depends_on:
      - build
    command: node lib-cjs/index.js

